name: Complete Fetch

on: [workflow_dispatch]

jobs:
  do-fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Fetch & Deploy Changes
        run: |
          git fetch origin gh-pages:gh-pages
          ./workflow-fetch-all.sh
