name: Complete Fetch

on:
  workflow_dispatch:
    inputs:
      skipExisting:
        description: 'Skip existing terms'
        default: true
        type: boolean

jobs:
  do-fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Fetch & Deploy Changes
        run: |
          if [ "${{ inputs.skipExisting }}" == true ]; then
            export BANNERWEB_SKIP_EXISTING=1
          fi
          git fetch origin gh-pages:gh-pages
          ./workflow-fetch-all.sh
