name: Periodic Fetch

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  periodic-fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Fetch & Deploy Changes
        run: |
          git fetch origin gh-pages:gh-pages
          ./workflow-run.sh "Periodic fetch ($(date +'%F %H:%M:%S') UTC)" fetch-last 3
